CREATE TABLE IF NOT EXISTS specialties
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name CHARACTER VARYING(50) NOT NULL,
    CONSTRAINT pk_specialties
        PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS skills
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name CHARACTER VARYING(50) NOT NULL,
    CONSTRAINT pk_skills
        PRIMARY KEY (id)
);

CREATE TYPE STATUS AS ENUM ('ACTIVE', 'DELETED');
CREATE TABLE IF NOT EXISTS developers
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name   CHARACTER VARYING(50) NOT NULL,
    last_name    CHARACTER VARYING(50) NOT NULL,
    specialty_id INTEGER,
    status       STATUS                NOT NULL,
    CONSTRAINT pk_developers
        PRIMARY KEY (id),
    CONSTRAINT specialty_developer_fk
        FOREIGN KEY (specialty_id) REFERENCES specialties
);

CREATE TABLE IF NOT EXISTS developer_skills
(
    developer_id BIGINT,
    skill_id     INTEGER,
    CONSTRAINT developer_skills_developer_fk
        FOREIGN KEY (developer_id) REFERENCES developers,
    CONSTRAINT developer_skills_skill_fk
        FOREIGN KEY (skill_id) REFERENCES skills
);